### ISSUE TITLE
Realtime

### ISSUE THREAD

**Issue by AbhayNawathey** [develersrl/angular-flot#15]
Can I use this library to update data/dataset via socket.io?

**Comment by lvillani** [comment]
Yes, that's precisely how we use the library in our application. Depending on how frequently you update the dataset you may incur a huge performance penalty, though. You basically have to do the same as http://www.flotcharts.org/flot/examples/realtime/index.html but by updating a scope variable. In our application we receive new data from socket.io every 2 to 5 seconds and in our case it works just fine. I'm not sure about heavier workloads.

**Comment by AbhayNawathey** [comment]
Thanks but for some reason my chart doesn't plot any data it gives the canvas but not data

**Comment by lvillani** [comment]
I'm afraid I can't help with that. The code is really the same as a "static" plot, each time we receive new data from socket.io we update the scope variable which holds the dataset.
