### ISSUE TITLE
Wrap jQuery code in closure

### ISSUE THREAD

**Issue by tallsam** [develersrl/angular-flot#16]
```
(function($){
......
})(jQuery);
```

See: http://stackoverflow.com/questions/3579643/what-is-the-benefit-of-wrapping-a-jquery-function-in-a-closure

**Comment by lvillani** [comment]
Is it really needed in this context?

Our code is already wrapped in an Angular module and inner closures, I guess we are not polluting the global namespace? Also, I believe that in 99.99% of the cases '$' is generally known to be bound to jQuery or some alternative implementation, I wouldn't go to the extra mile unless strictly necessary.

**Comment by tallsam** [comment]
I'm not 100% sure, but I'm embedding angular inside drupal 7 and for some reason it doesn't recognise $. Wrapping the angular app will probably fix the problem application wide. Pretend this didn't happen :P
