### ISSUE TITLE
Add plotclick event to the charts

### ISSUE THREAD

**Issue by mikkysati** [develersrl/angular-flot#17]
I have set clickable to true and tried binding plotclick to element in the flot directive but still plotclick is not triggered(I am using pie charts)

**Comment by jbeharrell** [comment]
Make sure that clickable is set in both the grid and series options.

**Comment by lvillani** [comment]
@mikkysati did you manage to solve the problem with @jbeharrell's tip?

**Comment by lvillani** [comment]
Assuming the problem was solved. I'm closing this issue to keep the bug tracker clean but feel free to reopen if necessary.
