### ISSUE TITLE
Flot plugin for plotting textual data or categories not working

### ISSUE THREAD

**Issue by cuongvv** [develersrl/angular-flot#19]
I modify your example/ index.html, try to using textual data or categories but not working,
```javascript
<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta charset="utf-8">
    <title>angular-flot example</title>
</head>
<body>
    <div ng-controller="FlotCtrl">
        <flot dataset="dataset" options="options" height="480px"></flot>
        <div id="legend" style="width: 200px; height: 200px;"></div>
    </div>

    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.resize.min.js"></script>
    <script src="http://www.flotcharts.org/flot/jquery.flot.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.18/angular.min.js"></script>
    <script src="../angular-flot.js"></script>

    <script src="app.js"></script>
</body>
</html>
```

**Comment by lvillani** [comment]
It seems your snippet is incomplete. Please post a full source code example reproducing the problem, including the JavaScript part.

**Comment by cuongvv** [comment]
Here demo: http://captheme.com/chart/example/
Reference demo: http://www.flotcharts.org/flot/examples/categories/index.html

**Comment by lvillani** [comment]
Yup, I can reproduce the issue locally. I can't work on this *right now* but I'll see what I can do later this or next week.

**Comment by lvillani** [comment]
Sorry for the delay, I'm still alive and kicking but I can't give you an exact timeframe as to when this issue will be fixed.

**Comment by lvillani** [comment]
@cuongvv Ah, I think I found the error. If you look the source code of the example at <http://www.flotcharts.org/flot/examples/categories/index.html> we see the dataset defined as

```javascript
var data = [ ["January", 10], ["February", 8], ["March", 4], ["April", 13], ["May", 17], ["June", 9] ];
```

And then used as

```javascript
$.plot("#placeholder", [ data ], { // Omissis
```

Which means that the dataset is wrapped inside another array. To make your example work you'd have to define the dataset as:

```javascript
$scope.dataset = [[["January", 10], ["February", 8], ["March", 4], ["April", 13], ["May", 17], ["June", 9]]];
```

(notice the additional pair of square brackets).

I'm adding a new example to the `examples` directory.
