### ISSUE TITLE
Examples on different charts

### ISSUE THREAD

**Issue by maeishoj** [develersrl/angular-flot#20]
I'd like to thank the creator for this directive, but almost no example is provided.

I would like for instance to make a donut chart, but can't seem to figure out how the options have to be applied here.. 

Anyone?

**Comment by lvillani** [comment]
Using this directive is no different than using regular Flot. You pass the `dataset` and `options` objects expected by `$.plot` on the scope as shown in the example.

Using a different chart type boils down to referencing the plugin's .js file somewhere in your page and adding the necessary entries to the `options` object, just like regular Flot (as shown by the provided example that uses the "resize" plugin).
