### ISSUE TITLE
Propagating events to the controller 

### ISSUE THREAD

**Issue by itsik-avidan-hp** [develersrl/angular-flot#21]
Is there a way to bind the 'plothover' and 'plotclick' events and to expose them using a callback to the controller ?
Since the events logic should be specific to the controller containing the directive, to logic for the events should be by the controller. the event binding is quite simple using element.bind("plotclick", func()) and available to expose to the controller

**Comment by lvillani** [comment]
Not yet at the moment. I'll have to expose them as "onplotclick" and "onplothover" attributes. I'll see if I can allocate some time to implement this.

**Comment by itsikavidan** [comment]
will a PR will help ? I can try and push on up

**Comment by lvillani** [comment]
Sure, I would gladly accept a PR, just make sure to change the CoffeeScript file.

**Comment by lvillani** [comment]
@itsik-avidan-hp @itsikavidan Are you working on this? I managed to allocate a slot to work on this issue. Since I would also like to remove the dependency on CoffeeScript I would like to avoid stepping on your toes.

**Comment by itsikavidan** [comment]
The code is ready, from some reason I can't push a new branch and create the PR

**Comment by lvillani** [comment]
@itsikavidan Shall I commit something similar on the branch that removes the CoffeeScript dependency?

**Comment by itsikavidan** [comment]
the PR was created
