### ISSUE TITLE
Angular Flot with Flot Animator

### ISSUE THREAD

**Issue by Mr-Anonymous** [develersrl/angular-flot#29]
Thank you for this angular plugin. Is there a way to integrate [Flot Animator] (http://www.codicode.com/art/jquery_flot_animator.aspx?utm_source=jquer.in&utm_medium=website&utm_campaign=content-curation) with this? 

According to the docs, to add the flot animation with that plugin, I need to change the plot function from :
```
var plot = $.plot($("#myChart"), [{ data : ... }]); 
```
To:
```
var plot = $.plotAnimator($("#myChart"), [{ data : ... }]);
```

Not sure how to do that with Angular Flot where all I do now is add 'angular-flot' to app dependancies and include the flot chart in template. Can you help me here please?

**Comment by lvillani** [comment]
There are currently no plan to support plotAnimator. However, you can fork angular-flot and replace the call to $.plot to $.plotAnimator there.
