### ISSUE TITLE
Chart not rendering correctly if element is invisible

### ISSUE THREAD

**Issue by chrisparton1991** [develersrl/angular-flot#33]
I'm having issues with my Flot chart's labels rendering incorrectly. Note the inconsistent alignment along the x axis at 07/13 and 01/14, and the indentation issue along the y axis.
![fail](https://cloud.githubusercontent.com/assets/13063119/13339603/250ef850-dc7e-11e5-8c5d-7e086981f336.png).

I made a change to angular-flot that essentially wraps the `link` function in an interval that waits for the plot element to be visible:

```
link: function (scope, element, attributes) {
  var interval = setInterval(function() {
    if ($(element).is(':visible')) {
      clearInterval(interval);
      onLink(scope, element, attributes);
    }
  }, 50);
}
```

This fixes my issue:
![success](https://cloud.githubusercontent.com/assets/13063119/13339679/9388f92a-dc7e-11e5-8431-a7ee77239b92.png)

I'm no front end expert, and this polling loop feels like a workaround, but I couldn't find another way to make my charts work reliably. Perhaps there is a better way of achieving this?

**Comment by lvillani** [comment]
Is the element initially hidden?

**Comment by chrisparton1991** [comment]
Yes, via ng-show. Although the behaviour is the same even without ng-show. We do have a subtle animation effect on entry, so it would be initially hidden by that.

**Comment by lvillani** [comment]
The default behaviour for ng-show is to set `display: none` on the element, removing it from layout calculations, that is probably what's tripping Flot when it has to place labels near the chart area. What happens if you set `visibility: hidden` instead?

**Comment by chrisparton1991** [comment]
Apologies for not getting back to you sooner. The behaviour is the same when setting visibility: hidden, or even removing ng-show altogether. Having said that, there may be something else causing the element to be hidden. We're using ui-router, perhaps that has something to do with it.

**Comment by lvillani** [comment]
That's weird and it's a case I never encountered. I'd have to investigate. Can you send me a minimal test case that reproduces the problem?

**Comment by chrisparton1991** [comment]
I've got a minimal test case ready. It took me a while to get around to it because it's not my primary project at work. Thanks for taking the time to help me out, I appreciate it.
[issue-33-test-case.zip](https://github.com/develersrl/angular-flot/files/162343/issue-33-test-case.zip)

I've discovered that this issue goes away when the ngAnimate module is removed. The module isn't used anywhere in the code, so it must be some kind of initialisation routine within ngAnimate that's causing the issue.

The test case consists of an index.html, an angular module+controller in app.module.js, and some supporting libraries (angular, angular-animate, angular-flot, flot, flot-resize & jquery).

Running the app as is will cause the issue to occur. Commenting out lines 26 and 28 of `app.module.js` (i.e. removing the timeout) will cause the issue not to occur.

Removing line 6 (i.e. the 'ngAnimate' dependency) also fixes the issue, regardless of whether the timeout is used or not. Therefore, this may not be an issue with angular-flot at all, but a compatibility issue between flot and ngAnimate.

I'd love to hear your thoughts on the matter.

**Comment by lvillani** [comment]
Thanks a lot for taking the time to make the test case! I'll try to look into this issue this Friday.

**Comment by lvillani** [comment]
Sorry for being late. I'm quite busy at the moment, I hope to be able to review this next week.

**Comment by chrisparton1991** [comment]
No problem, I'm pretty busy too, so I understand it's difficult to find time for this.

**Comment by lvillani** [comment]
I'll post my findings so far:
* Setting `width` and `height` on the `flot` element has no effect.
* Setting `!important` on `.flot-chart` CSS rule has no effect;
* Updating to the latest version of Angular, Flot, jQuery has no effect.

There's definitely something with ngAnimate though. If I enable paint rectangles in Chrome I can see the chart flashing with the wrong size (100x100) and then resizing to be 800x200 in the very next frame *but only if ngAnimate is enabled* (but notice how Chrome calculates the wrong size of the bounding box in this case)

Also see the following screen recording (please note that this may be deleted at any time): https://dl.dropboxusercontent.com/u/8255353/issue-33-chrome-layers.mov

**Comment by chrisparton1991** [comment]
Thanks for investigating, that screen recording is really interesting; it's got me flummoxed. One option on my side is to remove ngAnimate as a dependency (which will require removing or rewriting one other module that depends on it).

Still, it'd be interesting to know why ngAnimate is sinking its claws into the chart. I've looked at the ngAnimate documentation. It seems like all it does is add CSS classes such as `ng-enter` and `ng-leave` to elements when they are added/removed.

I added the following CSS to see if I could catch any flashes that would indicate that these classes were being added, but it doesn't seem like they are:

```CSS
.ng-enter, .ng-enter-active, .ng-leave, .ng-leave-active {
    border: 100px solid #f0f !important;
    background: #f0f !important;
}
```

**Comment by chrisparton1991** [comment]
This issue no longer applies to me, so I'm closing it. Thanks for the help @lvillani, I'm still none the wiser as to what causes this issue. Ah well, can't win them all :)

**Comment by joaoGabrielSalgado** [comment]
I know this issue is closed but i got myself into the same situation and as a solution i put a timeout before the data be ploted. I set the 'ng-show = true' with some variable and after when i will make the plot.setData(myData) i encapsulate with a timeout, like this:

`$ctrl.varOnDOM = true; //ng-show = true
$timeout(function(){
      $ctrl.myPlot.setData($ctrl.myData); // put your data
      $ctrl.myPlot.setupGrid();
      $ctrl.myPlot.draw();
}); `

And works, i think that the graph was been constructed out of DOM, so it was unconfigured
