### ISSUE TITLE
Minified js in bower 

### ISSUE THREAD

**Issue by akkumar** [develersrl/angular-flot#46]
It would be great to have a minified version in bower for the given release. 
Currently the tree looks as below: 

$ tree -L 10 bower_components/angular-flot/
bower_components/angular-flot/
├── angular-flot.js
├── AUTHORS
├── bower.json
├── CHANGELOG.md
├── CONTRIBUTING.md
├── example
│   ├── app.js
│   └── index.html
├── LICENSE.txt
├── logo.svg
├── package.json
└── README.md

It would be useful to have angular-flot.min.js as well.

**Comment by lvillani** [comment]
Hey @akkumar, sorry for being late. I think it's a good idea. I'm scheduling this to happen this Friday or next Friday at worst.

**Comment by lvillani** [comment]
Hey @akkumar, I released version 0.0.17 that should fix this issue.
