### ISSUE TITLE
Not connecting between points in time domain 

### ISSUE THREAD

**Issue by MuhammadElhrz** [develersrl/angular-flot#47]
I am using the x-axis in time domain and showing it in days but the lines between points is drawn if only there is data in two days that comes after each other but if there is data in a day and the other data after it by two days it shows points only but doesnt draw lines between these two points, what is the fix of that?

**Comment by lvillani** [comment]
Does it work with regular Flot?

**Comment by MuhammadElhrz** [comment]
Yes it was an error in the array of data i am passing to it, thanks alot for the quick reply
